### ISSUE TITLE
Possibly relax package_info_plus requirement?

### ISSUE THREAD

**Issue by valerauko** [fluttercommunity/wakelock_plus#14]
package_info_plus released 5.0. If it works with this package, please relax the requirement.

**Comment by NicolasDionB** [comment]
You can check the following Pull Request for progress on this: #13

**Comment by vbuberen** [comment]
` If it works with this package, please relax the requirement.`
Have you seen the changelogs for `package_info_plus`? 
Package is not compatible at the moment because of min Dart version. 
Why not check release notes and requirements before opening such issues?

**Comment by valerauko** [comment]
Fixed by #17
