### ISSUE TITLE
Update js to 0.7.0

### ISSUE THREAD

**Issue by xVemu** [fluttercommunity/wakelock_plus#20]
**flutter_native_splash** requires **js** version 0.7.0, so it makes it incompatible with **wakelock_plus**, because it depends on version 0.6.3

**Comment by diegotori** [comment]
@xVemu thanks for bringing that up. I'm gonna upgrade it and raise a PR shortly.

**Comment by diegotori** [comment]
Will show up in version `1.1.5`.
