### ISSUE TITLE
Upgrade dependency version for package_info_plus

### ISSUE THREAD

**Issue by FredslundMagnus** [fluttercommunity/wakelock_plus#30]
package_info_plus: ">=4.0.2 <6.0.0" should probably be updated to allow for the new package_info_plus 6.0.0

**Comment by arabnology** [comment]
Same here, we need that ASAP.

**Comment by dghub-founder** [comment]
Same here

**Comment by a-v-ebrahimi** [comment]
Same here, please update, thanks.

**Comment by lurongshuang** [comment]
+1

**Comment by iseebi** [comment]
+1

**Comment by navaronbracke** [comment]
This was updated at HEAD, but a new release is still pending it seems. @diegotori Any estimates on when a new release will be published?

**Comment by diegotori** [comment]
Addressed in version `1.2.0`.
