### ISSUE TITLE
package_info_plus: ">=4.0.2 <6.0.0" prevent other packages from updating

### ISSUE THREAD

**Issue by arabnology** [fluttercommunity/wakelock_plus#36]
package_info_plus: ">=4.0.2 <6.0.0" should probably be updated to allow for the new package_info_plus 6.0.0 and to allow update the other packages that depend on it, like Google Maps and Firebase. It is a very important update.

**Comment by diegotori** [comment]
@arabnology addressed in version `1.2.0`.
