### ISSUE TITLE
invalid source release, info_plus

### ISSUE THREAD

**Issue by cksoft0807** [fluttercommunity/wakelock_plus#42]
Hi,

with wake_lock_plus since 1.2.x i get the following error, when building for android.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':package_info_plus:compileReleaseJavaWithJavac'.
> error: invalid source release: 17

1.6 with package_info_plus 4.2.0 compiling fine

**Comment by diegotori** [comment]
@cksoft0807 this library from version `1.2.0`, along with `package_info_plus` from `6.0.0` and higher, now requires at least Java 17.

Please upgrade Java to that version in order to continue building for Android.

**Comment by trapeye** [comment]
I already upgrade to jdk 22, still get this problem, did I do wrong?
