### ISSUE TITLE
package_info_plus 7.0.0 not supporting.

### ISSUE THREAD

**Issue by romaCaldeira** [fluttercommunity/wakelock_plus#45]
Because every version of xpto from path depends on package_info_plus 7.0.0 and wakelock_plus >=1.2.2 depends on package_info_plus ^6.0.0, xpto from path is incompatible with
  wakelock_plus >=1.2.2.

 package_info_plus: ">=6.0.0 <7.0.0" ->  package_info_plus: ">=6.0.0 <8.0.0"

**Comment by diegotori** [comment]
@romaCaldeira Added in version `1.2.4`.

**Comment by romaCaldeira** [comment]
thank you very much

**Comment by moshOntong-IT** [comment]
> @romaCaldeira Added in version `1.2.4`.

I think we need to make the constraint ... < 9.0.0

**Comment by moshOntong-IT** [comment]
> > @romaCaldeira Added in version `1.2.4`.
> 
> I think we need to make the constraint ... < 9.0.0

or ... <= 8.0.0

**Comment by moshOntong-IT** [comment]
> @romaCaldeira Added in version `1.2.4`.

I have this issue 
[ISSUE](https://github.com/media-kit/media-kit/issues/794)

I think we have to update as well the constraint into ... <= 8.0.0 or ... < 9.0.0
