### ISSUE TITLE
 Unable to establish connection on channel: "dev.flutter.pigeon.wakelock_plus_platform_interface.WakelockPlusApi.toggle".

### ISSUE THREAD

**Issue by MauroGentile** [fluttercommunity/wakelock_plus#47]
I am using the HERE Flutter sdk and getting this error in the terminal.
Any idea what this may due to?

**Comment by thomasklaush** [comment]
The same on 1.2.4

**Comment by MauroGentile** [comment]
Hello Diego, 

yes, i confirm that by upgrading the library the issue i had got fixed. Thank you!

**Comment by abhishek-singh-cashify** [comment]
wakelock_plus:
    dependency: "direct main"
    description:
      name: wakelock_plus
      sha256: "14758533319a462ffb5aa3b7ddb198e59b29ac3b02da14173a1715d65d4e6e68"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.5"
I am using the latest version but still encountering this connection issues, due to this my build is not crash free.
