### ISSUE TITLE
Need the dependency for package_info_plus to be <= 8.0.0 not < 8.0.0

### ISSUE THREAD

**Issue by ChrisMICDUP** [fluttercommunity/wakelock_plus#50]
I'm deep down the Apple xcprivacy rabbit hole and getting this:

Because wakelock_plus >=1.2.4 depends on package_info_plus >=6.0.0 <8.0.0 and micdup_app depends on package_info_plus ^8.0.0, wakelock_plus >=1.2.4 is forbidden.

I'll downgrade package_info_plus to 7.0.0 and cross my fingers, but thought you should know.

**Comment by provokateurin** [comment]
No the constraint should be <9.0.0 to allow all 8.x.x versions.

**Comment by moshOntong-IT** [comment]
> No the constraint should be <9.0.0 to allow all 8.x.x versions.

So can someone update the constraint then

**Comment by provokateurin** [comment]
https://github.com/fluttercommunity/wakelock_plus/pull/52 someone did it already, it just needs to be reviewed, merged and released.
