### ISSUE TITLE
Switching from wakelock to wakelock_plus does not work

### ISSUE THREAD

**Issue by bloemy7** [fluttercommunity/wakelock_plus#53]
Hi,

I just upgraded my package from wakelock to wakelock_plus, but the exact same code (minus class name changes, i.e `Wakelock` to `WakelockPlus`) is resulting in the wakelock not working as expected on iOS and Android.

It's not keeping the screen on.
Is there a known issue here?
I'm on `wakelock_plus` 1.1.4 due to some other dependency issues, is there a known problem with that version of the package or not?

Thanks a lot.

**Comment by fettespferd** [comment]
Hey, yes there were some recent updates so that upgrading to the version 1.2.4. is necessary. Due to restrictions I have in FlutterFlow I can currently also not make it work.

**Comment by bloemy7** [comment]
Thanks - it was indeed fixed in that release.
