### ISSUE TITLE
The getter 'EXECUTION_STATE' isn't defined for the class 'WakelockPlusWindowsPlugin'.  - 'WakelockPlusWindowsPlugin'

### ISSUE THREAD

**Issue by gabrielsolomon** [fluttercommunity/wakelock_plus#57]
I tried to upgrade our project to flutter 3.0 but we now get the following error:

```
wakelock_plus_windows_plugin.dart:24:11: Error: The getter 'EXECUTION_STATE' isn't defined for the class 'WakelockPlusWindowsPlugin'.
 - 'WakelockPlusWindowsPlugin' is from 'package:wakelock_plus/src/wakelock_plus_windows_plugin.dart' ('/C:/Users/Solomon/AppData/Local/Pub/Cache/hosted/pub.dev/wakelock_plus-1.2.5/lib/src/wakelock_plus_windows_plugin.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'EXECUTION_STATE'.
          EXECUTION_STATE.ES_CONTINUOUS | EXECUTION_STATE.ES_DISPLAY_REQUIRED);
          ^^^^^^^^^^^^^^^
```

Is there something we could do to avoid the error?

**Comment by raaja-guidely** [comment]
yes i too got this error

**Comment by zionnite** [comment]
i'm having same issue,
please, anyone able to resolved it?

**Comment by diegotori** [comment]
Please run `flutter pub upgrade` when updating versions.

This is primarily due to the `win32` plug-in. Upgrading it will also upgrade that dependency as well.

**Comment by zionnite** [comment]
> Please run `flutter pub upgrade` when updating versions.
> 
> This is primarily due to the `win32` plug-in. Upgrading it will also upgrade that dependency as well.

Thanks have done so, and it worked very well but however I'm noticing some things I need to create my own issue so it will be addressed there

**Comment by gabrielsolomon** [comment]
Thank you! It worked
