### ISSUE TITLE
Not working in android while app is in Background

### ISSUE THREAD

**Issue by harshmdr-devslane** [fluttercommunity/wakelock_plus#69]
Can we leverage the package while android app is background with help of `flutter_background`? If yes, How?

**Comment by diegotori** [comment]
@harshmdr-devslane unfortunately, your proposal is out of scope for this project.

Long story short, this library is meant to keep your screen awake for all platforms and not just Android. You're more than welcome to create a separate library that uses this and `flutter_background` to achieve your objective.
