### ISSUE TITLE
Can't be installed

### ISSUE THREAD

**Issue by ciriousjoker** [fluttercommunity/wakelock_plus#8]
Because every version of wakelock_plus depends on package_info_plus ^4.0.2 and project_name depends on package_info_plus ^3.0.2, wakelock_plus is forbidden.
So, because project_name depends on wakelock_plus ^1.1.1, version solving failed.
exit code 1

We depend on `device_info_plus: ^9.0.3`. Is this solvable?

**Comment by diegotori** [comment]
I'll address this later tonight.

**Comment by ciriousjoker** [comment]
Thanks for the effort, but I'm an idiot, i misread "package_info_plus" as another package, which was already on the newest version.

Sorry for bothering you!
